// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AButtonGroup: typeof import('ant-design-vue/es')['ButtonGroup']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ControlOutlined: typeof import('@ant-design/icons-vue')['ControlOutlined']
    ExportOutlined: typeof import('@ant-design/icons-vue')['ExportOutlined']
    FileOutlined: typeof import('@ant-design/icons-vue')['FileOutlined']
    FolderOpenOutlined: typeof import('@ant-design/icons-vue')['FolderOpenOutlined']
    FundViewOutlined: typeof import('@ant-design/icons-vue')['FundViewOutlined']
    ImportOutlined: typeof import('@ant-design/icons-vue')['ImportOutlined']
    RedoOutlined: typeof import('@ant-design/icons-vue')['RedoOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveOutlined: typeof import('@ant-design/icons-vue')['SaveOutlined']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    UndoOutlined: typeof import('@ant-design/icons-vue')['UndoOutlined']
    ZoomInOutlined: typeof import('@ant-design/icons-vue')['ZoomInOutlined']
    ZoomOutOutlined: typeof import('@ant-design/icons-vue')['ZoomOutOutlined']
  }
}
